### PR TITLE
Finished second task

### PR DESCRIPTION
**Pull request by Leakhtrict**

### CODE REVIEW

**Comment by MaksimViarenich** [comment]
According to Technical requirement you don't need logic for Sign Up and forget password.

**Comment by MaksimViarenich** [comment]
Снимок экрана 2020-02-24 в 21 48 49

**Comment by MaksimViarenich** [comment]
Can't find filters
Снимок экрана 2020-02-24 в 20 28 30

**Comment by MaksimViarenich** [comment]
Can't find logic for remove also
Снимок экрана 2020-02-24 в 20 43 37

**Comment by MaksimViarenich** [comment]
It should be Page, not just tooltip)
Снимок экрана 2020-02-24 в 21 59 18

**Comment by Leakhtrict** [comment]
Ok, I'll try to fix things that you mentioned

**Comment by Leakhtrict** [comment]
Tell me please, if I draw something that is not in TR does it affect my mark?

**Comment by MaksimViarenich** [comment]
image

**Comment by MaksimViarenich** [comment]
image

**Comment by MaksimViarenich** [comment]
remove old mocks please)

**Comment by MaksimViarenich** [comment]
Still can't find this point
image

**Comment by MaksimViarenich** [comment]
Can't find this button also)
image

**Comment by MaksimViarenich** [comment]
Now your mark is 7.

**Comment by Leakhtrict** [comment]
> Now your mark is 7.

tried to fix mistakes again

**Comment by MaksimViarenich** [comment]
Merge PR, please!

**Pull request merged**
